minimum_pre_commit_version: "2.9.0"
exclude: "^tests/data/golden"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        exclude: "^.benchmarks/"
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: file-contents-sorter
        args: [--unique]
        files: '\.gitignore'
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0"
    hooks:
      - id: prettier
  - repo: https://github.com/ikamensh/flynt/
    rev: "1.0.1"
    hooks:
      - id: flynt
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1"
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml"]
        exclude: "^src/talonfmt/_compat_singledispatchmethod\\.py$"
        additional_dependencies:
          - "types_click"
          - "types_pyyaml"
